name: Count Files on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  count-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Count files
        run: |
          FILE_COUNT=$(find . -type f | wc -l)
          echo "🔢 Total number of files: $FILE_COUNT"
